---
- name: Backup sources.list
  ansible.builtin.copy:
    src: /etc/apt/sources.list
    dest: /etc/apt/sources.list.backup
- name: Delete sources.list
  ansible.builtin.file:
    path: /etc/apt/sources.list
    state: absent
- name: Create aliyun sources.list from a template
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'

  